language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source=core manage.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: PqeiMLIzmymRN1Mi39H+nxA1plORwmhL6zm2xGD1XA5ULqmGevrfQmmGSYwpZPzVri/5qacCZGn4u3yM04d3H0NWoVGuNJEkPlZfQA6UCNx2SNUvn3PXaKIioKX+6iyqoaGYYl5BAC1p2atk0RV0/O6j+/vr2/LiMkN8yW6u0PI=
  app: face-off-staging
  on:
    repo: excellalabs/face-off
  run: python manage.py migrate
