language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  -"./manage.py test core"
  -coverage run --source=face_it manage.py test core

after_success:
  coveralls