language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install coveralls
script: coverage run --source=core manage.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: baf4a384-0a09-45b6-ae78-b0e836c3b530
  app: col-league-staging
  on:
    repo: madridsoccer5/face_it
  run: "python manage.py migrate"
